### ISSUE TITLE
Videolist demo - controls & list should fade out

### ISSUE THREAD

**Issue by nicolsc** [joshfire/joshfire-framework#1]
http://framework.joshfire.com/examples/videolist/public/index.leanback.html

set time out to fade out controls & video list
fade in on user action

**Comment by sylvinus** [comment]
use/write adapters/browser/utils/activitymonitor.js

**Comment by jpvincent** [comment]
- should autostart + fullscreen

**Comment by jpvincent** [comment]
video list auto fade out remains to implment
