### ISSUE TITLE
VideoPlayer send the same event for onPlaying() and onPlay()

### ISSUE THREAD

**Issue by tbassetto** [joshfire/joshfire-framework#41]
When playing a video, the framework should send us these events:
- play (video asked to be played)
- loading (video loading)
- ready (video canPlay)
- playing (at last, video started playing)

Problem: if you look at _videoplayer.js_, the same event ("playing") is sent for the first and last step... So when receiving 'playing' we can't be sure the video is really playing.

The fix is quite simple but the consequences could be dramatic.

**Comment by steren** [comment]
Is there any way anybody could unassign me or close this issue?

**Comment by steren** [comment]
Wow this was really magic. I have no idea how this happened

**Comment by sylvinus** [comment]
But.. It's `Important`!

**Comment by sylvinus** [comment]
(and... dramatic, @tbassetto ? :-)

**Comment by fradinni** [comment]
Hum... just seen i'm still on that repo as well...
Are you trying revive this Framework ? :)

**Comment by steren** [comment]
I got unassigned right after my comment. If you did something you were fast. If GitHub did some natural language processing, I am very impressed. Probably it's just that I should not have been allowed to be an assignee, and updating the issue also updated this field.

**Comment by sylvinus** [comment]
Is there any way anybody could assign me to this issue?

**Comment by sylvinus** [comment]
Doesn't work...

**Comment by steren** [comment]
Well, you are already unassigned :)
